# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo My Gradle Azure Pipeline
  displayName: 'Run a one-line script'
- script: gradle build
  displayName: 'Building gradle application'
- script: gradle run
  displayName: 'Running gradle application'